[package]
authors = ['Parity Technologies <admin@parity.io>']
edition = '2018'
name = 'node-portablegabi-runtime-wasm'
version = '0.1.0'

[dependencies.node-portablegabi-runtime]
default-features = false
path = '..'

[features]
default = []
std = ['node-portablegabi-runtime/std']

[workspace]
members = []

[lib]
crate-type = ['cdylib']

[profile.release]
lto = true
panic = 'abort'
