on:
  push:
    branches:
      - master
  release:
    types: [created]

name: Release

jobs:
  buildDocker:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t kiltprotocol/portablegabi-node .

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo $DOCKER_PASS | docker login --username=$DOCKER_USER --password-stdin

      - name: Tag, and push image to Docker Hub
        env:
          DOCKER_REPOSITORY: kiltprotocol/portablegabi-node
        run: |
          docker tag kiltprotocol/portablegabi-node $DOCKER_REPOSITORY:latest
          docker push $DOCKER_REPOSITORY:latest
